# Generated by Django 4.0.4 on 2022-06-02 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gymbo', '0004_equipment_force_muscle_alter_session_user_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='primary_muscle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='primary_muscle', to='gymbo.muscle'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='secondary_muscles',
            field=models.ManyToManyField(related_name='secondary_muscle', to='gymbo.muscle'),
        ),
        migrations.DeleteModel(
            name='ExerciseMuscle',
        ),
    ]
